### ISSUE TITLE
Move to Qt5!

### ISSUE THREAD

**Issue by SafaAlfulaij** [ahmadnourallah/theTranslator#1]
Hello! :-)

This looks very nice, but nowadays people are using Qt5 for almost all programs.
It would be great if the app could move to PyQt5.

And, I should be able to run the app without installing it. It's Python!
Had to comment out line 34 and change line 35 in theTranslator file.

Otherwise, nice work! Needs some modifications here and there ;-)

**Comment by ahmadnourallah** [comment]
- you are right maybe be moved to Qt5 good and maybe not !
i have worked with qt4 for a long time and i don't think i will move to qt5 right now but i will look in the issue 
- in this point i agree with you 100% so i will provide that as soon as possible
- all modifications are welcomed feel freely to push your pull requests in any time :) 
thanks for your interest
