### ISSUE TITLE
What are the features and how to use your library?

### ISSUE THREAD

**Issue by JafferWilson** [ahmadnourallah/theTranslator#2]
You have mentioned 

> Translate your text with many amazing features (for Gnu/Linux system only)  

But what are they and how to run you repository. Kindly update your readme file.

**Comment by ahmadnourallah** [comment]
First thanks for your interest,
Simply it's a texts translator uses google translator and yandex (i updated the readme file as you asked).
You can read **installing** section in readme file to know how to install it.

**Comment by JafferWilson** [comment]
It is ok but how to use it in Python as a library and functions? Is there a common method that will help? Can you explain one example for testing on the commandline Python? Hope to hear from you soon.

**Comment by ahmadnourallah** [comment]
Yes you can use functions in translateapi/translator.py file to use methods that used in application gui, there are three functions you can use it the first it's name is Googletranslate this function used to translate text via google translate website, it's syntax:
```
Googletranslate(string, to_language="auto", from_language="auto")
```
the second one is `Yandextranslate` it's use to translate text via yandex translator, it's syntax:
```
Yandextranslate(string, to_language)
```
the last function is `LanguageDetect` it's used to detect language via yandex api, it's syntax:
```
LanguageDetect(string)
```
I hope the explanation is useful.

**Comment by JafferWilson** [comment]
Thank you

**Comment by ahmadnourallah** [comment]
you are welcome don't forget to star project 😄
